version: '3.0'
services:
  maradb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE= ${DB_NAME}
    ports:
      - '3306:3306'
#  ugh-green:
#    container_name: ugh-green
#    image: ugh-back
#    expose:
#      - 8081
#  ugh-blue:
#    container_name: ugh-blue
#    image: ugh-back
#    expose:
#      - 8081
#  nginx:
#    container_name: nginx
#    image: chosh040/my-nginx
#    ports:
#      - '80:80/tcp'
#      - '443:443'