spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      repositories:
        enabled: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  docker:
    compose:
      lifecycle-management: none
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
server:
  port: ${SERVER_PORT}
