spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      repositories:
        enabled: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  docker:
    compose:
      lifecycle-management: none
jwt:
  secret-key: ${JWT_SECRET_KEY}
  expired_time: 86400000
  refresh_time: 1209600033

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

server:
  port: 8080