spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: ${DEV_REDIS_PORT}
      repositories:
        enabled: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DEV_DB_HOST}
    username: ${DEV_DB_USER}
    password: ${DEV_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  docker:
    compose:
      lifecycle-management: start_and_stop
jwt:
  secret-key: ${DEV_JWT_SECRET_KEY}
  expired_time: 86400000
  refresh_time: 1209600033

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

server:
  port: ${DEV_SERVER_PORT}
